### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Vaopresso** [dvomaks/laravel-livecoin#1]
Did you make this?

**Comment by dvomaks** [comment]
Yes

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
Awesome, well hey i really like what youve done. Been working on a few small parts best i can without ruining any of your work. Would love to run a few ideas by you if you have some time. Happy to tip ya some coin for your expert attention sir :)

**Comment by Vaopresso** [comment]
Awesome, well hey i really like what youve done. Been working on a few small parts best i can without ruining any of your work. Would love to run a few ideas by you if you have some time. Happy to tip ya some coin for your expert attention sir :)
